### ISSUE TITLE
Connect Django 4.0 in Azure Web App Linux/Container to Azure SQL not working

### ISSUE THREAD

**Issue by 0xUnicorn** [microsoft/mssql-django#114]
I have spend the past days trying to accomplish the following:

Deploy Django 4.0 app to Azure Web App Linux from Azure DevOps Pipeline.
Connect the app to Azure SQL.

It all works fine locally when starting manage.py it connects to the Azure SQL.

My issue though is I'm using Azure Artifacts for a private PyPI, so I can't use oryx for building my env, since PipAuthenticate isn't supported.
If I build my antenv in the build pipeline on the agent and archiving it with my artifact, I'm missing a glibc2.30 library on the Web App because of pip creating links to libs.

I then tried deploying as a Docker container in a Web App Linux for container, as this should have fixed all of my issues. This though resulted in an ImportError which can't find "mssql" and then my container shuts down, so I can't troubleshoot.

If I build and start my container locally it works all fine.

I found out I'm not alone with this frustrating task of endless problems.
https://stackoverflow.com/questions/60554719/python-webapp-on-azure-app-service-writing-to-a-sql-server-database-horribly-co

Then I stumbled across your repo: https://github.com/Azure-Samples/azure-sql-db-django

I really hope you can help me someway or another before I give up and deploy a mysql or postgresql database. (So far I've released 50 times trying to deploy a working state, each release takes +10 minutes)

EDIT:
`Successfully installed mssql-django-1.1.2 pyodbc-4.0.32 pytz-2021.3` - From DevOps build pipeline (running Dockerfile)

Dockerfile
```
FROM python:3.9-slim-bullseye

ARG INDEX_URL
ENV PIP_EXTRA_INDEX_URL=$INDEX_URL

ENV PYTHONUNBUFFERED 1

WORKDIR /src

COPY src/ /src

RUN apt-get update && apt-get install -y curl gnupg build-essential
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update && ACCEPT_EULA=Y apt-get install -y --no-install-recommends --allow-unauthenticated msodbcsql17 mssql-tools unixodbc-dev
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc

RUN pip install -U pip
RUN pip install -r requirements.txt
RUN pip install -r requirements-mssql.txt

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

```

requirements-mssql.txt
```
pyodbc==4.0.*
mssql-django==1.1.*
```
db_settings.py
```
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': '<db-name>',
        'USER': os.environ.get('MSSQL_USER'),
        'PASSWORD': os.environ.get('MSSQL_PASS'),
        'HOST': '<db-name>.database.windows.net',
        'PORT': '',

        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
}
```

**Comment by 0xUnicorn** [comment]
All it took was opening this issue and it resolved it self. Not entirely, but almost.

I created a new commit and triggered my build pipeline building the container, and afterwards a deploy pipeline for publishing the container to ACR.

Then my App Service for container started the docker image and after some time, it returned this error.
So I send a new request to my App Service and this time it started the container and served my site, with a mssql DB connection.

Do you have any suggestions why it would first give me a timeout when starting the container for the first time, and how to mitigate it?

```bash
2022-03-14T18:26:32.221471389Z Traceback (most recent call last):
2022-03-14T18:26:32.221475089Z   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
2022-03-14T18:26:32.230459752Z     self.run()
2022-03-14T18:26:32.230476452Z   File "/usr/local/lib/python3.9/threading.py", line 910, in run
2022-03-14T18:26:32.241348529Z     self._target(*self._args, **self._kwargs)
2022-03-14T18:26:32.241361829Z   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
2022-03-14T18:26:32.241367329Zfn(*args, **kwargs)
2022-03-14T18:26:32.241371529Z   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 127, in inner_run
2022-03-14T18:26:32.241375829Z     self.check_migrations()
2022-03-14T18:26:32.241379929Z   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 505, in check_migrations
2022-03-14T18:26:32.241384229Z     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
2022-03-14T18:26:32.241388329Z   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__
2022-03-14T18:26:32.241392529Z     self.loader = MigrationLoader(self.connection)
2022-03-14T18:26:32.241407729Z   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 53, in __init__
2022-03-14T18:26:32.241411829Z     self.build_graph()
2022-03-14T18:26:32.241415329Z   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 223, in build_graph
2022-03-14T18:26:32.241419129Z     self.applied_migrations = recorder.applied_migrations()
2022-03-14T18:26:32.241422929Z   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
2022-03-14T18:26:32.241426629Z     if self.has_table():
2022-03-14T18:26:32.241430229Z   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 55, in has_table
2022-03-14T18:26:32.241433929Z     with self.connection.cursor() as cursor:
2022-03-14T18:26:32.241437529Z   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 25, in inner
2022-03-14T18:26:32.241441329Z     return func(*args, **kwargs)
2022-03-14T18:26:32.241444929Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 270, in cursor
2022-03-14T18:26:32.241448629Z     return self._cursor()
2022-03-14T18:26:32.241453329Z   File "/usr/local/lib/python3.9/site-packages/mssql/base.py", line 230, in _cursor
2022-03-14T18:26:32.241457130Z     conn = super()._cursor()
2022-03-14T18:26:32.241460830Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 246, in _cursor
2022-03-14T18:26:32.241464630Z     self.ensure_connection()
2022-03-14T18:26:32.241468130Z   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 25, in inner
2022-03-14T18:26:32.241471830Z     return func(*args, **kwargs)
2022-03-14T18:26:32.241475430Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 230, in ensure_connection
2022-03-14T18:26:32.241479130Z     self.connect()
2022-03-14T18:26:32.241483230Z   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
2022-03-14T18:26:32.241487130Z     raise dj_exc_value.with_traceback(traceback) from exc_value
2022-03-14T18:26:32.241490830Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 230, in ensure_connection
2022-03-14T18:26:32.241494630Z     self.connect()
2022-03-14T18:26:32.241498130Z   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 25, in inner
2022-03-14T18:26:32.241501830Z     return func(*args, **kwargs)
2022-03-14T18:26:32.241505430Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 211, in connect
2022-03-14T18:26:32.241509130Z     self.connection = self.get_new_connection(conn_params)
2022-03-14T18:26:32.241512830Z   File "/usr/local/lib/python3.9/site-packages/mssql/base.py", line 329, in get_new_connection
2022-03-14T18:26:32.241516630Z     conn = Database.connect(connstr,
2022-03-14T18:26:32.241523630Z django.db.utils.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
```

**Comment by absci** [comment]
Does your Azure SQL have enabled features like auto-pause? I think some people had this timeout issue when auto-pause is enabled. You could also use a custom manage.py file to retry the connection if needed.

**Comment by 0xUnicorn** [comment]
> Does your Azure SQL have enabled features like auto-pause? I think some people had this timeout issue when auto-pause is enabled. You could also use a custom manage.py file to retry the connection if needed.

Thanks, of course it makes sense. I've disabled auto-pause now. Thanks for the advice

**Comment by wied03** [comment]
I think there should be another option besides turning off auto pause, which has some value. It seems like the only reason this is a problem is a login timeout exception that results from this has error code 08001, which is not considered retryable by mssql-django's `_transient_error_numbers`. The https://azure.microsoft.com/en-us/documentation/articles/sql-database-develop-csharp-retry-windows/ URL referenced in the code also seems to be a different page now.

Any opposition to adding 08001 to the transient list?

![image](https://github.com/microsoft/mssql-django/assets/297123/3b05bff5-a5fa-41fe-8ded-7afb21a6421d)
