### ISSUE TITLE
Receive 'Invalid object name' error while trying to make query

### ISSUE THREAD

**Issue by Sourdough1882** [microsoft/mssql-django#261]
**Question**

I ran into the issue while trying to get information from a view of Microsoft SQL Server where I can't select anything with db manager using model which was created using **inspectdb** utility, which is strange for me because it can create required models with all fields for it to work, but while making queries it halts telling me that I provide invalid object name.

Console output:
---
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Python\dashbord\dash_virtual\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\User\Desktop\Python\dashbord\dash_virtual\lib\site-packages\mssql\base.py", line 619, in execute
    return self.cursor.execute(sql, params)
pyodbc.ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'report_tvshows_2023_view'. (208) (SQLExecDirectW); [42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\User\Desktop\Python\dashbord\dash_virtual\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\User\Desktop\Python\dashbord\dash_virtual\lib\site-packages\django\db\models\query.py", line 646, in get
    num = len(clone)
  File "C:\Users\User\Desktop\Python\dashbord\dash_virtual\lib\site-packages\django\db\models\query.py", line 376, in len
    self._fetch_all()
  File "C:\Users\User\Desktop\Python\dashbord\dash_virtual\lib\site-packages\django\db\models\query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\User\Desktop\Python\dashbord\dash_virtual\lib\site-packages\django\db\models\query.py", line 87, in iter
    results = compiler.execute_sql(
  File "C:\Users\User\Desktop\Python\dashbord\dash_virtual\lib\site-packages\django\db\models\sql\compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\User\Desktop\Python\dashbord\dash_virtual\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\User\Desktop\Python\dashbord\dash_virtual\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\User\Desktop\Python\dashbord\dash_virtual\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\User\Desktop\Python\dashbord\dash_virtual\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\User\Desktop\Python\dashbord\dash_virtual\lib\site-packages\django\db\utils.py", line 91, in exit
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\Desktop\Python\dashbord\dash_virtual\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\User\Desktop\Python\dashbord\dash_virtual\lib\site-packages\mssql\base.py", line 619, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'report_tvshows_2023_view'. (208) (SQLExecDirectW); [42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")
----

I use Django 4.2 version with latest mssql-django driver, could that be the issue? I have tried to use 'schema.table' specified in Meta class, which gave no results. 

**Relevant Issues and Pull Requests**
 #183 appears to have the same issue

**Comment by Sourdough1882** [comment]
Solved issue by providing a proper table schema model's meta class. For those who stumbled into the same problem I have the problem is not in a driver or configuration (I tested on ODBC 17 and Native drivers) but in specifying schema for your table in a model.

```python
class ModelName(models.Model):
    class Meta:
        db_table = "[schema].[table]" # Make sure to enclose schema and table/view in square brackets
        managed = False
```

Used packages:
django-4.1.8
mssql-django-1.2
pyodbc-4.0.39
pytz-2023.3
