### ISSUE TITLE
django.db.utils.NotSupportedError: SQL Server v16 is not supported.

### ISSUE THREAD

**Issue by root4417** [microsoft/mssql-django#270]
There are some features which are not supported yet. Please check the [Limitations](https://github.com/microsoft/mssql-django#limitations) first to see if your bug is listed.

**Software versions**
* Django: 4.0
* mssql-django: latest
* python: 3
* SQL Server: Microsoft SQL Server 2022 (RTM-CU4) (KB5026717) - 16.0.4035.4 (X64) 
	May  1 2023 10:34:45 
	Copyright (C) 2022 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 20.04.6 LTS) <X64>
* OS: MacOS (Docker container for MSSQL)

**Database Connection Settings**
`
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': env('DB_NAME'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'OPTIONS': {
             'driver': 'ODBC Driver 18 for SQL Server',
             "extra_params": 'Encrypt=yes;Trusted_Connection=no;TrustServerCertificate=yes;Connection Timeout=300;Authentication=SQLPassword',
             'MARS_Connection': 'True',
         }
    },
}

`

**Problem description and steps to reproduce**
Version 16 is not supported.

**Expected behavior and actual behavior**
It should work

**Error message/stack trace**
```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/muhammad/PycharmProjects/agent_performance_service/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/muhammad/PycharmProjects/agent_performance_service/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 137, in inner_run
    self.check_migrations()
  File "/Users/muhammad/PycharmProjects/agent_performance_service/venv/lib/python3.10/site-packages/django/core/management/base.py", line 576, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/Users/muhammad/PycharmProjects/agent_performance_service/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/muhammad/PycharmProjects/agent_performance_service/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/Users/muhammad/PycharmProjects/agent_performance_service/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/Users/muhammad/PycharmProjects/agent_performance_service/venv/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
    if self.has_table():
  File "/Users/muhammad/PycharmProjects/agent_performance_service/venv/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 57, in has_table
    with self.connection.cursor() as cursor:
  File "/Users/muhammad/PycharmProjects/agent_performance_service/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/muhammad/PycharmProjects/agent_performance_service/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 284, in cursor
    return self._cursor()
  File "/Users/muhammad/PycharmProjects/agent_performance_service/venv/lib/python3.10/site-packages/mssql/base.py", line 247, in _cursor
    conn = super()._cursor()
  File "/Users/muhammad/PycharmProjects/agent_performance_service/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 260, in _cursor
    self.ensure_connection()
  File "/Users/muhammad/PycharmProjects/agent_performance_service/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/muhammad/PycharmProjects/agent_performance_service/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
    self.connect()
  File "/Users/muhammad/PycharmProjects/agent_performance_service/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/muhammad/PycharmProjects/agent_performance_service/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 227, in connect
    self.init_connection_state()
  File "/Users/muhammad/PycharmProjects/agent_performance_service/venv/lib/python3.10/site-packages/mssql/base.py", line 414, in init_connection_state
    val = self.get_system_datetime()
  File "/Users/muhammad/PycharmProjects/agent_performance_service/venv/lib/python3.10/site-packages/mssql/base.py", line 430, in get_system_datetime
    if self.sql_server_version <= 2005:
  File "/Users/muhammad/PycharmProjects/agent_performance_service/venv/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/muhammad/PycharmProjects/agent_performance_service/venv/lib/python3.10/site-packages/mssql/base.py", line 451, in sql_server_version
    raise NotSupportedError('SQL Server v%d is not supported.' % ver)
django.db.utils.NotSupportedError: SQL Server v16 is not supported.
```

**Any other details that can be helpful**
_sql_server_versions = {
        9: 2005,
        10: 2008,
        11: 2012,
        12: 2014,
        13: 2016,
        14: 2017,
        15: 2019,
        # 16: 2022,
    }
    
    Just added the 16 and It works like a charm.

**Comment by mShan0** [comment]
Are you sure you're on the latest mssql-django? We added support for 2022 in v1.2
