### ISSUE TITLE
Managed Identity & Web App for Containers

### ISSUE THREAD

**Issue by djtje12** [microsoft/mssql-django#275]
I'm having an issue while using the mssql-django package when running Web App for Containers & user assigned identity.
For some reason it looks like the SQL Server details aren't used correctly when using "Authentication=ActiveDirectoryMsi".

`
django.db.utils.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
`

However when using the direct token method with DefaultAzureCredential().get_token('https://database.windows.net/.default').token i'm able to get an accesstoken from the managed identity i'm using. 
`
DATABASES = {
    "default": {
        "ENGINE": "mssql",
        "NAME": "my_db",
        "HOST": "my_db.database.windows.net",
        "TOKEN": DefaultAzureCredential().get_token('https://database.windows.net/.default').token,
        "PORT": "1433",
        "OPTIONS": {
            "driver": "ODBC Driver 17 for SQL Server",
        },
    },
}
`

Is there something going wrong when passing in the server details (when its running in a container) where it's trying to connect to or am i missing an important detail?

**Software versions**
* Django: 4.2
* mssql-django: 1.3
* python: 3.10.11
* SQL Server: Azure Sql Database (Basic Sku)

**Database Connection Settings**
`
DATABASES = {
    "default": {
        "ENGINE": "mssql",
        "NAME": "my_db",
        "HOST": "my_db.database.windows.net",
        "PORT": "1433",
        "OPTIONS": {
            "driver": "ODBC Driver 17 for SQL Server",
            "extra_params": "Authentication=ActiveDirectoryMsi",
        },
    },
}
`

**Problem description and steps to reproduce**
Create a new Django application, use a Dockerfile and upload the container to ACR. Deploy to Azure App Service for Containers with an user assigned identity, give the managed identity Azure AD Admin permissions on Azure SQL Server & put the settings as above.

**Expected behavior and actual behavior**
Django uses the managed identity to directly connect to the database and not get a login timeout. Same as how it gets the connection when directly getting an accesstoken.

**Error message/stack trace**
`
2023-06-05T11:16:19.567529066Z Watching for file changes with StatReloader
2023-06-05T11:16:57.086538663Z Exception in thread django-main-thread:
2023-06-05T11:16:57.086590864Z Traceback (most recent call last):
2023-06-05T11:16:57.086598964Z   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
2023-06-05T11:16:57.088913495Z     self.connect()
2023-06-05T11:16:57.088934495Z   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
2023-06-05T11:16:57.088941796Z     return func(*args, **kwargs)
2023-06-05T11:16:57.088955396Z   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 270, in connect
2023-06-05T11:16:57.088961196Z     self.connection = self.get_new_connection(conn_params)
2023-06-05T11:16:57.088965296Z   File "/usr/local/lib/python3.10/site-packages/mssql/base.py", line 366, in get_new_connection
2023-06-05T11:16:57.088969296Z     conn = Database.connect(connstr, **args)
2023-06-05T11:16:57.088973196Z pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
2023-06-05T11:16:57.088977196Z
2023-06-05T11:16:57.088980796Z The above exception was the direct cause of the following exception:
2023-06-05T11:16:57.088984696Z
2023-06-05T11:16:57.088988196Z Traceback (most recent call last):
2023-06-05T11:16:57.088991896Z   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2023-06-05T11:16:57.089043497Z     self.run()
2023-06-05T11:16:57.089052397Z   File "/usr/local/lib/python3.10/threading.py", line 953, in run
2023-06-05T11:16:57.089056297Z     self._target(*self._args, **self._kwargs)
2023-06-05T11:16:57.089059997Z   File "/usr/local/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
2023-06-05T11:16:57.089063797Z     fn(*args, **kwargs)
2023-06-05T11:16:57.089067397Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 136, in inner_run
2023-06-05T11:16:57.089071297Z     self.check_migrations()
2023-06-05T11:16:57.089120898Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 574, in check_migrations
2023-06-05T11:16:57.089202299Z     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
2023-06-05T11:16:57.089215599Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 18, in __init__
2023-06-05T11:16:57.089220799Z     self.loader = MigrationLoader(self.connection)
2023-06-05T11:16:57.089224699Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 58, in __init__
2023-06-05T11:16:57.089228599Z     self.build_graph()
2023-06-05T11:16:57.089232299Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 235, in build_graph
2023-06-05T11:16:57.091379128Z     self.applied_migrations = recorder.applied_migrations()
2023-06-05T11:16:57.091414429Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
2023-06-05T11:16:57.091419529Z     if self.has_table():
2023-06-05T11:16:57.091423529Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 57, in has_table
2023-06-05T11:16:57.091453929Z     with self.connection.cursor() as cursor:
2023-06-05T11:16:57.091460229Z   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
2023-06-05T11:16:57.091464529Z     return func(*args, **kwargs)
2023-06-05T11:16:57.091468429Z   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 330, in cursor
2023-06-05T11:16:57.091472329Z     return self._cursor()
2023-06-05T11:16:57.091476129Z   File "/usr/local/lib/python3.10/site-packages/mssql/base.py", line 259, in _cursor
2023-06-05T11:16:57.091479930Z     conn = super()._cursor()
2023-06-05T11:16:57.091483630Z   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 306, in _cursor
2023-06-05T11:16:57.091487530Z     self.ensure_connection()
2023-06-05T11:16:57.091491130Z   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
2023-06-05T11:16:57.091494930Z     return func(*args, **kwargs)
2023-06-05T11:16:57.091498730Z   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 288, in ensure_connection
2023-06-05T11:16:57.091502930Z     with self.wrap_database_errors:
2023-06-05T11:16:57.091506630Z   File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
2023-06-05T11:16:57.091510330Z     raise dj_exc_value.with_traceback(traceback) from exc_value
2023-06-05T11:16:57.091513930Z   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
2023-06-05T11:16:57.091517730Z     self.connect()
2023-06-05T11:16:57.091521430Z   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
2023-06-05T11:16:57.091525330Z     return func(*args, **kwargs)
2023-06-05T11:16:57.091529030Z   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 270, in connect
2023-06-05T11:16:57.091532830Z     self.connection = self.get_new_connection(conn_params)
2023-06-05T11:16:57.091536430Z   File "/usr/local/lib/python3.10/site-packages/mssql/base.py", line 366, in get_new_connection
2023-06-05T11:16:57.091540230Z     conn = Database.connect(connstr, **args)
2023-06-05T11:16:57.091543930Z django.db.utils.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
`

**Any other details that can be helpful**
Using the direct token method inside of the same container works, using a service principal with password also works. So connectivity wise it looks like all the prereqs are met.

When checking the audit logs on the SQL Server & DB there are no incoming connections coming from the WebApp when using "Authentication=ActiveDirectoryMsi".

**Comment by mShan0** [comment]
Thanks for the detailed report. Will be looking into this. Just curious, have you tried setting `Encrypt=Yes`? If not, can you try that out?

**Comment by djtje12** [comment]
> Thanks for the detailed report. Will be looking into this. Just curious, have you tried setting `Encrypt=Yes`? If not, can you try that out?

`Encrypt=Yes` in the extra_params gives the exact same behavior.

**Comment by djtje12** [comment]
> Thanks for the detailed report. Will be looking into this. Just curious, have you tried setting `Encrypt=Yes`? If not, can you try that out?

Did you already had time to look into this issue?

**Comment by mShan0** [comment]
We've been looking into what could be causing this. Have you tried connecting directly using pyODBC or ODBC? Does it work through that?

**Comment by djtje12** [comment]
I did not try it with pyODBC or ODBC, but seeing that when I generate a valid token with the managed identity in a direct way and then using that token I can successfully connect, doesn't the issue lay in how mssql-django generates it's token.

Using mssql-django and a valid token works as intended, so what would be the benefit of me testing with pyODBC or ODBC?

**Comment by gabohc** [comment]
@djtje12 I tried directly with pyODBC and it did not work either

Following this official guide and example: https://learn.microsoft.com/en-us/azure/app-service/tutorial-connect-msi-azure-database?tabs=sqldatabase%2Csystemassigned%2Cpython%2Ccli#3-modify-your-code

Using the token as instructed in the example works well
