### ISSUE TITLE
ODBC SQL type -150 is not yet supported

### ISSUE THREAD

**Issue by Augis363** [microsoft/mssql-django#307]
There are some features which are not supported yet. Please check the [Limitations](https://github.com/microsoft/mssql-django#limitations) first to see if your bug is listed.

**Software versions**
* Django: 4.0.10
* mssql-django: 1.3.0
* python: 3.8.8
* SQL Server: Azure SQL server 
* OS: Debian GNU/Linux 10 (buster) 10

**Table schema and Model**

Django default User model
**Database Connection Settings**
`
// Paste your database settings from Settings.py here.
`DATABASES = {
    "default": {
        "ENGINE": "mssql",
        "NAME" <name>,
        "HOST":  <host>,
        "PORT": "1433",
        "USER": <user>,
        "PASSWORD":  <pass>,
        "OPTIONS": {
            "driver": "ODBC Driver 17 for SQL Server",
        },
    }
}

USE_TZ = True
TIME_ZONE = "Europe/Amsterdam"

**Problem description and steps to reproduce**

Just running django server and trying to log in to adming page throws "ODBC SQL type -150 is not yet supported" 
**Expected behavior and actual behavior**

Login successful
**Error message/stack trace**

[2023-10-19 08:46:43 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2023-10-19 08:46:43 +0000] [8] [INFO] Listening at: http://0.0.0.0:80 (8)   
[2023-10-19 08:46:43 +0000] [8] [INFO] Using worker: sync
[2023-10-19 08:46:43 +0000] [14] [INFO] Booting worker with pid: 14
[2023-10-19 08:46:43 +0000] [15] [INFO] Booting worker with pid: 15
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/usr/app/.venv/lib/python3.8/site-packages/django/db/utils.py", line 98, in inner
    return func(*args, **kwargs)
  File "/usr/app/.venv/lib/python3.8/site-packages/mssql/base.py", line 664, in fetchmany
    return self.format_rows(self.cursor.fetchmany(chunk))
pyodbc.ProgrammingError: ('ODBC SQL type -150 is not yet supported.  column-index=2  type=-150', 'HY106')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/app/.venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/app/.venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/app/.venv/lib/python3.8/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/app/.venv/lib/python3.8/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/app/.venv/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 440, in login
    return LoginView.as_view(**defaults)(request)
  File "/usr/app/.venv/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/app/.venv/lib/python3.8/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/app/.venv/lib/python3.8/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/app/.venv/lib/python3.8/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/app/.venv/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/app/.venv/lib/python3.8/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/app/.venv/lib/python3.8/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/app/.venv/lib/python3.8/site-packages/django/contrib/auth/views.py", line 67, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/app/.venv/lib/python3.8/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/app/.venv/lib/python3.8/site-packages/django/views/generic/edit.py", line 152, in post
    if form.is_valid():
  File "/usr/app/.venv/lib/python3.8/site-packages/django/forms/forms.py", line 205, in is_valid
    return self.is_bound and not self.errors
  File "/usr/app/.venv/lib/python3.8/site-packages/django/forms/forms.py", line 200, in errors
    self.full_clean()
  File "/usr/app/.venv/lib/python3.8/site-packages/django/forms/forms.py", line 434, in full_clean
    self._clean_form()
  File "/usr/app/.venv/lib/python3.8/site-packages/django/forms/forms.py", line 455, in _clean_form
    cleaned_data = self.clean()
  File "/usr/app/.venv/lib/python3.8/site-packages/django/contrib/auth/forms.py", line 217, in clean
    self.user_cache = authenticate(
  File "/usr/app/.venv/lib/python3.8/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper    
    return func(*func_args, **func_kwargs)
  File "/usr/app/.venv/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 77, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/usr/app/.venv/lib/python3.8/site-packages/django/contrib/auth/backends.py", line 42, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/usr/app/.venv/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 46, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/usr/app/.venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/app/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 492, in get
    num = len(clone)
  File "/usr/app/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 302, in __len__
    self._fetch_all()
  File "/usr/app/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/app/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/usr/app/.venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1394, in execute_sql
    return list(result)
  File "/usr/app/.venv/lib/python3.8/site-packages/mssql/compiler.py", line 176, in _cursor_iter
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/usr/app/.venv/lib/python3.8/site-packages/mssql/compiler.py", line 176, in <lambda>
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/usr/app/.venv/lib/python3.8/site-packages/django/db/utils.py", line 98, in inner
    return func(*args, **kwargs)
  File "/usr/app/.venv/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/app/.venv/lib/python3.8/site-packages/django/db/utils.py", line 98, in inner
    return func(*args, **kwargs)
  File "/usr/app/.venv/lib/python3.8/site-packages/mssql/base.py", line 664, in fetchmany
    return self.format_rows(self.cursor.fetchmany(chunk))
django.db.utils.ProgrammingError: ('ODBC SQL type -150 is not yet supported.  column-index=2  type=-150', 'HY106')
**Any other details that can be helpful**

**Comment by mShan0** [comment]
Thanks for the report. Will be looking into this.

**Comment by mShan0** [comment]
Was it all admin users that cause this error?

**Comment by dauinsight** [comment]
Hi @Augis363, SQL type -150 is SQL_VARIANT

We are currently working on support for SQL_VARIANT and will update you when it is released. Thank you

**Comment by andrew-kyle92** [comment]
Has there been a fix for this, yet?

**Comment by absci** [comment]
There's already a [PR](https://github.com/mkleehammer/pyodbc/pull/1354) in `pyodbc` repo that adds support for SQL variant. Looks like it'll be merged soon. So, we just need to wait for a new pyodbc release.
