### ISSUE TITLE
Error on initial migration: Applying contenttypes.0001_initial...Traceback 

### ISSUE THREAD

**Issue by luizfelipevbll** [microsoft/mssql-django#36]
Using django 3.2 and mssql-django 1.0b1 I get the following error runing the first migrate

```sh
Operations to perform:
dj    |   Apply all migrations: admin, auth, contenttypes, sessions, silk
dj    | Running migrations:
dj    |   Applying contenttypes.0001_initial...Traceback (most recent call last):
dj    |   File "/backend/manage.py", line 21, in <module>
dj    |     main()
dj    |   File "/backend/manage.py", line 17, in main
dj    |     execute_from_command_line(sys.argv)
dj    |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
dj    |     utility.execute()
dj    |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
dj    |     self.fetch_command(subcommand).run_from_argv(self.argv)
dj    |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
dj    |     self.execute(*args, **cmd_options)
dj    |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
dj    |     output = self.handle(*args, **options)
dj    |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
dj    |     res = handle_func(*args, **kwargs)
dj    |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 244, in handle
dj    |     post_migrate_state = executor.migrate(
dj    |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
dj    |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
dj    |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
dj    |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
dj    |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
dj    |     state = migration.apply(state, schema_editor)
dj    |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/migration.py", line 126, in apply
dj    |     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
dj    |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/operations/models.py", line 528, in database_forwards
dj    |     alter_together(
dj    |   File "/usr/local/lib/python3.9/site-packages/mssql/schema.py", line 167, in alter_unique_together
dj    |     self.execute(sql)
dj    |   File "/usr/local/lib/python3.9/site-packages/mssql/schema.py", line 856, in execute
dj    |     sql = str(sql)
dj    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/ddl_references.py", line 201, in __str__
dj    |     return self.template % self.parts
dj    | **KeyError: 'include'**
```

**Comment by absci** [comment]
Django 3.2 is working with the latest `dev` branch. To try it out, you could `git clone` and `checkout` dev branch to a local directory and `pip install -e .` in that folder. 
Or you could use the previous version of Django `pip install django==3.1`
