### ISSUE TITLE
Migration issue - Django 3.2.3

### ISSUE THREAD

**Issue by pmasonBWC** [microsoft/mssql-django#50]
Hi,

Appreciate this is a Beta product; I'm trying to get the SQL script using "sqlmigrate" for a brand new, completely blank Django project with just the basic admin tools.

I'm getting this output, which indicates a failure in the mssql Schema.py file:

python3 manage.py sqlmigrate admin 0001_initial
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/pmason/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/pmason/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/pmason/.local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/pmason/.local/lib/python3.8/site-packages/django/core/management/commands/sqlmigrate.py", line 29, in execute
    return super().execute(*args, **options)
  File "/home/pmason/.local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/pmason/.local/lib/python3.8/site-packages/django/core/management/commands/sqlmigrate.py", line 65, in handle
    sql_statements = loader.collect_sql(plan)
  File "/home/pmason/.local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 351, in collect_sql
    state = migration.unapply(state, schema_editor, collect_sql=True)
  File "/home/pmason/.local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 118, in __exit__
    self.execute(sql)
  File "/home/pmason/.local/lib/python3.8/site-packages/mssql/schema.py", line 856, in execute
    sql = str(sql)
  File "/home/pmason/.local/lib/python3.8/site-packages/django/db/backends/ddl_references.py", line 201, in __str__
    return self.template % self.parts
KeyError: 'include'

When I try to run the migration I get the same sort of error:

python3 manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial...Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/pmason/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/pmason/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/pmason/.local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/pmason/.local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/pmason/.local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/pmason/.local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/home/pmason/.local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/pmason/.local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/pmason/.local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/pmason/.local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/pmason/.local/lib/python3.8/site-packages/django/db/migrations/operations/models.py", line 528, in database_forwards
    alter_together(
  File "/home/pmason/.local/lib/python3.8/site-packages/mssql/schema.py", line 167, in alter_unique_together
    self.execute(sql)
  File "/home/pmason/.local/lib/python3.8/site-packages/mssql/schema.py", line 856, in execute
    sql = str(sql)
  File "/home/pmason/.local/lib/python3.8/site-packages/django/db/backends/ddl_references.py", line 201, in __str__
    return self.template % self.parts
KeyError: 'include'

I don't want to allow Django to control the DB via migration, because it's an existing operational DB with an MS Access front end.  But I need the scripts for the admin functionality.

Something is going wrong in the interpretation of the models used in the admin tools.

In the meantime I'll reverse engineer a SQLite DB and see if I can connect with that.

**Comment by absci** [comment]
Hi, a new version of `mssql-django` (1.0rc1) released to PyPi, it should fix this error.

**Comment by pmasonBWC** [comment]
Thanks, will try it out a bit later.  For what it's worth I succesfully reverse engineered the tables the basic admin/auth functions produce and faked the migrations.  I'm planning on primarily using DB first ORM, not code first...but it's good to have it there just in case.
