### ISSUE TITLE
SMux Provider: Physical connection is not usable [xFFFFFFFF] & The cursor's connection has been closed

### ISSUE THREAD

**Issue by matthiasguentert** [microsoft/mssql-django#70]
I am desperately trying to migrate our mysql-based Django solution to an Azure SQL database. 

Steps I have performed: 

* Run `python manage.py dumpdata --format json --indent 2 C:\Temp\dumb.json` to backup data from source instance using MySQL backend. 

* Changed `settings.py` so it points to target Azure SQL database

```
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'sqldb-mydb',
        'USER': 'myuser@sql-myserver',
        'PASSWORD': '<hidden>',
        'HOST': 'sql-myserver.database.windows.net',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
			
            # Integer. Sets the timeout in seconds for the database connection process. Default value is 0 which disables the timeout.			
            'connection_timeout': '0',
			
            # Integer. Sets the times to retry the database connection process. Default value is 5.
            'connection_retries': '5',
			
            # Integer. Sets the back off time in seconds for reries of the database connection process. Default value is 5.
            'connection_retry_backoff_time': '5',
			
            # Integer. Sets the timeout in seconds for the database query. Default value is 0 which disables the timeout.
            'query_timeout': '0'
        }
    }
}

# Set this to False if you want to turn off pyodbc's connection pooling
DATABASE_CONNECTION_POOLING = True 
```

* Run `python manage.py migrate` to create schema on target database (Azure) 

* Run `python manage.py loaddata --format json --verbosity 3 C:\Temp\dumb.json` to restore data on target database. 

However, it fails with the following output

```
❯ python .\manage.py loaddata --format json --verbosity 3 C:\temp\dump.json
Time of launch 2021-10-11 14:30:19.403482

Loading 'C:\temp\dump' fixtures...
Checking 'C:\temp' for fixtures...
Installing json fixture 'dump' from 'C:\temp'.
Processed 58017 object(s).Traceback (most recent call last):
  File "C:\dev\venv\django2-dev\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\dev\venv\django2-dev\lib\site-packages\mssql\base.py", line 567, in execute
    return self.cursor.execute(sql, params)
pyodbc.Error: ('08S02', '[08S02] [Microsoft][ODBC Driver 17 for SQL Server]SMux Provider: Physical connection is not usable [xFFFFFFFF].  (-1) (SQLPrepare); [08S02] [Microsoft][ODBC Driver 17 for SQL Server]Unable to open a logical session (-1)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\dev\venv\django2-dev\lib\site-packages\django\db\models\sql\compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "C:\dev\venv\django2-dev\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\dev\venv\django2-dev\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\dev\venv\django2-dev\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\dev\venv\django2-dev\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\dev\venv\django2-dev\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\dev\venv\django2-dev\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\dev\venv\django2-dev\lib\site-packages\mssql\base.py", line 567, in execute
    return self.cursor.execute(sql, params)
django.db.utils.Error: ('08S02', '[08S02] [Microsoft][ODBC Driver 17 for SQL Server]SMux Provider: Physical connection is not usable [xFFFFFFFF].  (-1) (SQLPrepare); [08S02] [Microsoft][ODBC Driver 17 for SQL Server]Unable to open a logical session (-1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\dev\repos\<my-application>\backend\manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "C:\dev\venv\django2-dev\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\dev\venv\django2-dev\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\dev\venv\django2-dev\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\dev\venv\django2-dev\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "C:\dev\venv\django2-dev\lib\site-packages\django\core\management\commands\loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "C:\dev\venv\django2-dev\lib\site-packages\django\core\management\commands\loaddata.py", line 114, in loaddata
    self.load_label(fixture_label)
  File "C:\dev\venv\django2-dev\lib\site-packages\django\core\management\commands\loaddata.py", line 181, in load_label
    obj.save(using=self.using)
  File "C:\dev\venv\django2-dev\lib\site-packages\django\core\serializers\base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "C:\dev\venv\django2-dev\lib\site-packages\django\db\models\base.py", line 780, in save_base
    updated = self._save_table(
  File "C:\dev\venv\django2-dev\lib\site-packages\django\db\models\base.py", line 853, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "C:\dev\venv\django2-dev\lib\site-packages\django\db\models\base.py", line 903, in _do_update
    return filtered._update(values) > 0
  File "C:\dev\venv\django2-dev\lib\site-packages\django\db\models\query.py", line 760, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\dev\venv\django2-dev\lib\site-packages\django\db\models\sql\compiler.py", line 1471, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\dev\venv\django2-dev\lib\site-packages\django\db\models\sql\compiler.py", line 1145, in execute_sql
    cursor.close()
  File "C:\dev\venv\django2-dev\lib\site-packages\mssql\base.py", line 521, in close
    self.cursor.close()
pyodbc.ProgrammingError: Problem installing fixture 'C:\temp\dump.json': The cursor's connection has been closed.
```

The processing of these 58'000 items took around 2 hours, why I had to disable Azure's `auto-pause` feature as it broke my connection before. However, not it failed with the message above. 

These are the Azure SQL db service and compute tiers in use: 

- Service tier: General purpose (scalable compute and storage options) 
- Compute tier: Serverless 
- Max vCores: 4
- Min vCores: 0.5
- Data max size: 10 GB 
- Database is not zone redundant
- Backup: Locally-redundant backup storage 

Any help on this is greatly appreciated!!!!

**Comment by matthiasguentert** [comment]
This seems to be caused by pyodbc's connection pooling. When setting `DATABASE_CONNECTION_POOLING = False` it works. Why is that?

**Comment by absci** [comment]
Are you running this on Windows or Linux? Also, could you run `pip freeze`, It would be helpful to know the version of pyODBC, etc.
