### ISSUE TITLE
missing regex_clr.dll

### ISSUE THREAD

**Issue by graingert** [microsoft/mssql-django#84]
when running install_regex_clr I get a FileNotFoundError

```pytb
$ python api/manage.py install_regex_clr master
Traceback (most recent call last):
  File "/home/graingert/projects/ks-cohere/api/manage.py", line 44, in <module>
    main()
  File "/home/graingert/projects/ks-cohere/api/manage.py", line 40, in main
    execute_from_command_line(sys.argv)
  File "/home/graingert/.virtualenvs/ks-cohere/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/graingert/.virtualenvs/ks-cohere/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/graingert/.virtualenvs/ks-cohere/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/graingert/.virtualenvs/ks-cohere/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/graingert/.virtualenvs/ks-cohere/lib/python3.9/site-packages/mssql/management/commands/install_regex_clr.py", line 27, in handle
    connection.creation.install_regex_clr(database_name)
  File "/home/graingert/.virtualenvs/ks-cohere/lib/python3.9/site-packages/mssql/creation.py", line 114, in install_regex_clr
    assembly_hex=self.get_regex_clr_assembly_hex(),
  File "/home/graingert/.virtualenvs/ks-cohere/lib/python3.9/site-packages/mssql/creation.py", line 124, in get_regex_clr_assembly_hex
    with open(os.path.join(os.path.dirname(__file__), 'regex_clr.dll'), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/graingert/.virtualenvs/ks-cohere/lib/python3.9/site-packages/mssql/regex_clr.dll'
```

It seems it was removed here https://github.com/microsoft/mssql-django/commit/eaf27e543a61d234dfe750f70ccd44c059ed9af8

**Comment by absci** [comment]
I'll add this file to PyPi on the next release (end of January). 
Release 1.0 still have this file, so you could `pip install mssql-django==1.0` and use this version to install currently.

**Comment by graingert** [comment]
@absci there's a solution using VBScript here that might help if you don't want to ship a .dll?

https://renenyffenegger.ch/notes/development/databases/SQL-Server/T-SQL/functions/regexp/index

**Comment by graingert** [comment]
sadly no licence on those source files... yet: https://github.com/ReneNyffenegger/about-MSSQL/issues/1

**Comment by graingert** [comment]
The files are now available under the MIT license https://github.com/ReneNyffenegger/SQL-Server-helpers/tree/master/regexp

**Comment by absci** [comment]
> The files are now available under the MIT license https://github.com/ReneNyffenegger/SQL-Server-helpers/tree/master/regexp

Thanks, `regex_clr.dll` will be included in all future releases in PyPi. I'll also take a look of the `SQL-Server-helpers` repo you mentioned.

**Comment by absci** [comment]
Hi, for the latest release 1.1.2, the regex_clr.dll in included in the package.
