### ISSUE TITLE
UniqueConstraint creation with composite condition fails

### ISSUE THREAD

**Issue by Eboreg** [microsoft/mssql-django#91]
## The problem

We are unfortunately still running Django 2.2.24 (an upgrade is in the pipeline, but you know ...). DB is an Azure SQL Server instance. Backend is a completely fresh pip install of mssql-django 1.1.1. I am trying to create a conditional UniqueConstraint on model `schools.School`, looking like the following:

```python
class Meta:
    constraints = [
        models.UniqueConstraint(
            fields=["city", "name", "country"],
            condition=~Q(city=None) & ~Q(city=""),
            name="school__unique_city_name_country"
        ),
    ]
```

So the logic is: "only enforce this constraint if `city` is neither `None` nor an empty string".

The migration logic generated:

```python
migrations.AddConstraint(
    model_name='school',
    constraint=models.UniqueConstraint(condition=models.Q(models.Q(_negated=True, city=None), models.Q(_negated=True, city='')), fields=('city', 'name', 'country'), name='school__unique_city_name_country'),
)
```

On migration, it tries to execute: 

```tsql
CREATE UNIQUE INDEX [school__unique_city_name_country] 
ON [schools_school] ([city], [name], [country]) 
WHERE (
	NOT ([city] IS NULL) AND 
	NOT ([city] = '' AND [city] IS NOT NULL)
)
```

This results in the following:

```
Traceback (most recent call last):
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/mssql/base.py", line 577, in execute
    return self.cursor.execute(sql, params)
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'NOT'. (156) (SQLExecDirectW)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 40, in <module>
    execute_from_command_line(sys.argv)
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 232, in handle
    post_migrate_state = executor.migrate(
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/django/db/migrations/operations/models.py", line 827, in database_forwards
    schema_editor.add_constraint(model, self.constraint)
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/mssql/schema.py", line 1117, in add_constraint
    super().add_constraint(model, constraint)
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 345, in add_constraint
    self.execute(sql)
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/mssql/schema.py", line 1021, in execute
    cursor.execute(sql, params)
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/cacheops/transaction.py", line 97, in execute
    result = self._no_monkey.execute(self, sql, params)
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/klaatu/kod/edu-lms/.venv/lib/python3.8/site-packages/mssql/base.py", line 577, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'NOT'. (156) (SQLExecDirectW)")
```

The funny thing is, the exact same condition works just fine in a regular query; `School.objects.filter(~Q(city=None) & ~Q(city=""))` generates the SQL query (note that the `WHERE` clauses are identical):

```tsql
SELECT TOP 21 
	[schools_school].[id], [schools_school].[created], [schools_school].[updated], 
	[schools_school].[created_by_id], [schools_school].[name], [schools_school].[language], 
	[schools_school].[address], [schools_school].[zipcode], [schools_school].[city], 
	[schools_school].[municipality], [schools_school].[curriculum_id], [schools_school].[country], 
	[schools_school].[is_active], [schools_school].[comments] 
FROM [schools_school] 
WHERE (
	NOT ([schools_school].[city] IS NULL) AND 
	NOT ([schools_school].[city] = '' AND [schools_school].[city] IS NOT NULL)
) 
ORDER BY [schools_school].[name] ASC
```
... which gives the expected queryset as a result.

## The workaround

I was able to achieve the same result (I hope!) using the below constraint. Still thought I'd report this strange behaviour.

```python
class Meta:
    constraints = [
        models.UniqueConstraint(
            fields=["city", "name", "country"],
            condition=Q(city__gt=""),
            name="school__unique_city_name_country"
        ),
    ]
```

**Comment by rjschave** [comment]
@Eboreg 

You mentioned your condition works fine in a regular query, but not a unique constraint.  There seems to be a limitation on the keywords that can be used in the WHERE clause of unique constraints.  I learned that the OR keyword is not allowed ( more info here - https://github.com/wagtail/wagtail/issues/6393).  It's possible the NOT keyword is also not supported.  

I wonder if this project can detect this and write the clause another way or at least raise an error on the Django side.

**Comment by Eboreg** [comment]
@rjschave Thanks. Judging from [this](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql?view=sql-server-ver15#syntax-for-sql-server-and-azure-sql-database), it does indeed look like you're correct; filter predicates can only be joined by AND, and not prefixed by NOT. 

Of course, the condition in my initial constraint could be rewritten as:

```tsql
WHERE (
	([city] IS NOT NULL) AND 
	([city] <> '')
)
```

or something along those lines, which I guess should work.
